todogroup/ospology

- newsletter/2021-08-30.md
It looked like it's alphabetical, though it feels rude to insert at the beginning of the list. Let me know if it's instead by file editing order.
> Adding AWS SDE role

- newsletter/2021-08-30.md
Per TODOGroup Slack conversation.
> Proposing a link to an OpenSearch role

- newsletter/2021-09-27.md
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>
> Adding OSPOCon Europe to newsletter

- newsletter/2022-01-31.md
Description: I added a CFP link for Open Source Community Africa Festival.
> Add OSCA CFP

- newsletter/2022-01-31.md
Add article from Information Age about Mental Health and Open Source Software
> Add article about Mental Health and OSS

- newsletter/2022-02-22.md
Add meetup about OSPO happening on 9 March 2022
> Add Meetup about OSPOs

- newsletter/2022-02-22.md
Add kickoff of the study group
> Add IEEE study group for Open Source Software Project Governance

- newsletter/2022-02-22.md
I added FOSS Backstage to conferences.
> Add FOSS Backstage conference

- newsletter/2022-02-22.md
> Add CFP for Uptime

- ospo-mindmap/README.md
Touching up grammar and syntax. What a cool project! Thank you for sharing 😄
> Minor formatting to OSPO mind map

- newsletter/2022-05-31.md
Hopefully, I counted correctly, but I got a number 11.
> News letter 9 -> 11

- ospo-model/en/five-stage-OSPO-maturity-model.md
Documentation from the OSPO maturity model is shown in "The evolution of the OSPO" study. This commit also includes a suggested list of OSS Communities to engage on each of the stages. These OS communities are divided between (T-shaped OSPOs):
* Industry verticals
* Horizontal OSPO skills
> Add ospo maturity model documentation

- newsletter/2022-05-31.md
Add press release from Aiven about their recent raising of $210M to Invest in Sustainable Open Source Cloud
> Add Aiven's series D to invest in sustainable OS

- meetings/Sync Chapters/APAC-notes/April-Chinese.md
Translate April Meeting into Chinese.
Signed-off-by: Xiaoya <xiaoyaxiaesther@gmail.com>
> Translate APAC Sync April Meeting to Chinese.md

- ospology-live/framework.md
Add to ospology repo ospology.live framework idea for in-person semi-unconference meetings piloting in Europe first
> create ospology.live framework

- newsletter/2022-06-28.md
Signed-off-by: Ruth Ikegah <ruthikegah@gmail.com>
> Update Upcoming OSPO News

- ospo-mindmap/Content/ospomindmap.md
Incorporate work from Ibrahim Haddad ea. see [1].
[1]: https://github.com/ibrahimhaddad/publications/blob/master/Open%20Source%20Program%20Offices.pdf
Signed-off-by: Thomas Steenbergen <thomas_steenbergen@epam.com>
> ospomindmap: Update OSPO responsibilities

- ospo-mindmap/Content/ospomindmap.md
Added a couple of training courses (LFC 191 and LFC 194) and a sub-heading "Compliance Considerations" because the other branches have the same level headings and now the map has more consistent look. Let's discuss if the heading name is o.k. or if that needs to be changed.
> Small additions to the mindmap

- README.md
created a new PR that contains @sdake 's contribution ➡️ https://github.com/todogroup/ospology/pull/80
> update readme that contains steven contributions from previous PR

- ospo-mindmap/README.md
One section of the mind map is table data, but not formatted as tables.
Signed-off-by: Steven Dake <steven.dake@gmail.com>
> Reformat a table into tables

- newsletter/日本語版/2022-05-31.md
I translated the article into Japanese.
Could you please check this?
> Update 2022-05-31.md in Japanese version.

- newsletter/2022-06-28.md
> add new entries to june's newsletter

- newsletter/2022-06-28.md
Hope I'm not too late!
Signed-off-by: Justin Dorfman <justindorfman@gmail.com>
> Add link to blog article

- newsletter/2022-07-26.md
> add initial template for july's newsletter

- ospo-mindmap/Content/ospomindmap.md
Add initial level preview and link to multiple languages versions
> add initial level preview and link to languages

- newsletter/2022-06-28.md
- newsletter/2022-07-26.md
Add CFP link's for upcoming conferences where CFP is going to be closing soon.
Signed-off-by: Brad McCoy <bradmccoydev@gmail.com>
> Add cfp details to next newsletter

- newsletter/2022-07-26.md
Signed-off-by: Ruth Ikegah <ruthikegah@gmail.com>
> Update OSPO News

- ospo-mindmap/Content/ospomindmap.md
Added a size option: "- FTE team with virtual members from other teams"
Signed-off-by: Gilles Gravier <gilles@gravier.org>
> Updated ospomindmap.md

- newsletter/2022-07-26.md
> Update 2022-07-26.md newsletter

- local-meetups/framework.md
This framework defines the requirements to host and organize OSPO local meetups in local languages powered by TODO Group.
> Create framework for OSPO Local Meetups

- newsletter/日本語版/2022-06-28.md
@anajsana 
I re-created the PR.
Could you please check this?
> Update 2022-06-28.md in Japanese version (new). 

- newsletter/2022-08-30.md
> add august newsletter resources

- newsletter/2022-09-26.md
> add september osponews template

- newsletter/2022-09-26.md
> add september content for osponews

- newsletter/2022-08-25.md
Adding October's newsletter template so the community can start adding new content before the newsletter gets published by Tuesday 25th, October.
> Add october's newsletter template

- meetings/README.md
Add October's ospology recording video: Ways to define a metrics strategy in your OSPO https://youtu.be/e-V0EaYyl7I
> Add october's ospology recording video

- newsletter/2022-10-25.md
Hi @anajsana,
as discussed, I've added the FOSS Backstage CfP. 
Best,
Sven
> FOSS Backstage CfP

- newsletter/Spanish Version/2022-10-25.md
> create spanish newsletter for october issue

- newsletter/2022-11-29.md
This commit adds the template used on each newsletter so the community can start making editions and adding content.
> add template to work on nov newsletter content

- newsletter/2022-11-29.md
Signed-off-by: Ruth Ikegah <ruthikegah@gmail.com>
I edited and Updated the November newsletter.
> Update November Newsletter

- newsletter/2022-11-29.md
Signed-off-by: Sourav Das <souravcipher@gmail.com>
> add new job to nov newsletter

- newsletter/2022-11-29.md
Signed-off-by: Bill Mulligan <billmulligan516@gmail.com>
> Add Isovalent job posting

- newsletter/2022-11-29.md
> add more news to november newsletter

- meetings/Sync Chapters/APAC-notes/June-Chinese.md
Signed-off-by: donghui <977675308@qq.com>
> typo: 背景-->北京

- meetings/README.md
> add january ospology panel discussion topic

- README.md
- newsletter/README.md
- newsletter/newsletter-guidelines.md
- Updated revue to ghost link 
- Also, updated the youtube link
https://www.youtube.com/@ospology looks better!! : )
> Update Newsletter link

- ospology-live/framework.md
include OSPO Associate within OSPOlogyLive organizer qualifications
> include OSPO Associate within OSPOlogyLive organizer qualifications

- ospo-mindmap/Content/ospomindmap.md
OSPOs are a center of excellence and often collaborate with several other groups in the company. I added common stakeholders and partnerships that OSPOs interact with.
> OSPOMindMap Adding Common Stakeholders

- newsletter/2023-01-31.md
add ISPO WK creation in the cross-community newsletter section
> add ISPO WK creation at cross-community

- ospology-live/2023-january-netherlands/day2-best-practices-for-supporting-developers-to-contribute-to-open-source-and-or-innersource.md
> Add notes from innersource day 2 workshop

- ospology-live/2023-january-netherlands/day2-minimal-viable-ospo.md
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>
> Notes of day 2 workshop on a Minimal Viable OSPO

- ospology-live/2023-january-netherlands/day2-creating-an-open-source-strategy.md
add notes about creating an os strategy on day 2
Signed-off-by: Ana Jimenez Santamaria <anitajs95@gmail.com>
> add notes about os strategy day 2

- newsletter/2023-02-27.md
- newsletter/README.md
> Add new conference event in newsletter.

- newsletter/2023-02-27.md
> Add events to newsletter

- ospo-book/chapters/taxonomy.md
create taxonomy document to help reader navigate throughout the book
> [OSPO Book] create taxonomy document

- ospo-mindmap/Content/ospomindmap_jp.md
- ospo-mindmap/package.json
this adds a new md for the japanese version to fix the expand level bug and updates package.json
> fix expand level for mindmap japanese version

- ospo-book/chapters/glossary.md
This PR creates a glossary.md for the OSPO book.
As we agreed during our first OSPO Book Contributors call, here is the PR with the new section: The OSPO Book glossary. It also includes an introduction to clarify the kind of references we would like to cover and how to contribute with new definitions 👍
> [OSPO Book] Create glossary.md

- ospo-book/chapters/01-chapter.md
fixed some spelling errors
fixed typos
changed Programs to Program
> [OSPO Book] Update 01-chapter.md

- ospo-book/chapters/00-chapter.md
did some copy editing for the 00-chapter.md file
changed sentences so they're more clear
> [OSPO Book] Update 00-chapter.md

- ospo-book/docs/interview-questionnaire.md
This pull request contains a list of 13 questions to be used as a guide during the upcoming interviews to be scheduled during the months of April and May.
> [OSPO Book] Add list of questions for the ospo book interviews

- ospo-book/chapters/toc.md
Update TOC titles according to merged content and PRs
> [OSPO Book] Update toc.md

- ospo-book/AUTHORS.md
Since I have been contributing to the OSPO book, could I be added as Co-Author? Thanks.
> [OSPO Book] Add Jonas as Co-Author to AUTHORS.md

- .github/workflows/linter.yml
- ospo-book/content/en/_index.md
- ospo-book/content/en/references.md
This updates the configuration of the markdown linter in accordance with the changed location of the markdown files for the new website.
> OSPO-Book: update linter configuration

- ospo-book/content/en/glossary.md
This pr converts https://github.com/todogroup/ospology/pull/339/files into a duplicate
> Add new terms to glossary.md

- ospo-book/README.md
- ospo-book/content/en/00-chapter.md
- ospo-book/content/en/01-chapter.md
- ospo-book/content/en/02-chapter.md
- ospo-book/content/en/03-chapter.md
- ospo-book/content/en/_index.md
- ospo-book/content/en/toc.md
This PR suggest a couple of fixes for typos, spelling, style and removing a bit of redundancy to make things clearer and consistent. No changes to the content itself.
> [OSPO Book] Editorial changes

- ospo-book/content/en/01-chapter.md
There is quite some variety of names for the concept of an OSPO. Make this clear in the note about the naming.
> [OSPO Book] Expand note about naming OSPOs

- newsletter/2023-08-29.md
include monthly announcements, new ospo jobs and next ospology session details
> [Newsletter] Update 2023-08-29.md

- ospo-book/content/en/02-chapter.md
Assessing the value of contributions is important, but contributions are the second step for almost all organizations. The first step is consuming open source software, which comes with all kind of things an OSPO has to consider. This PR suggests an additional section about assessing the value of open source consumption, which could be seen as a prerequisite for considering contributions.
> [OSPO Book] Add section about assessing value of open source consumption

- ospo-book/config.toml
Set github_subdir = "ospo-book" 
Fix issue #383
> Update config.toml to set github_subdir

- ospo-book/content/en/01-chapter.md
This commit updates Chapter 1 to enhance clarity throughout the content and renames the 'Antipatterns' section to 'Recommendations'
> [OSPO Book] Small updates in Chapter 1 to enhance clarity

- ospo-book/content/en/02-chapter.md
Include new references, clarify assesment sections and complete appendix content
> [OSPO Book] Update chapter 2

- ospo-book/content/en/taxonomy.md
This commit updates the diagram with the new design and changes the anti-pattern section for recommendations
> [OSPO Book] update diagramand change the anti-pattern section

- ospo-book/content/en/01-chapter.md
> Fixed grammar in 01-chapter.md

- ospo-model/en/ospo-checklist.md
> Minor OSPO checklist grammar update

- newsletter/2024-01-30.md
See commit for details
Close #416
> Add upcoming events to Jan 30 2024 newsletter

- newsletter/2024-01-30.md
> Add jobs to Jan 30 2024 newsletter

- newsletter/2024-01-30.md
> Add E.ON job to Jan 30 2024 newsletter

- ospo-book/docs/meeting-notes/04-01-2024.md
Create meeting notes that mirror Google Doc used for meeting notes
> [OSPO Book] Create meeting notes folder and initial md file

- ospo-book/GOVERNANCE.md
Hey hope this is helpful as opposed to annoying! Just wanted to patch some typos I noticed when I was reading through some of the docs
> Minor typo fixes in GOVERNANCE.md

- ospo-book/GOVERNANCE.md
Reading the documentation on how to contribute to this project, I stumbled across a couple of typos and minor editorial issues that seemed like an easy-to-fix first issue... :smile:
> [OSPO Book] update GOVERNANCE.md

- ospo-book/content/en/use-cases.md
The OSPO End User Journey report highlights active Open Source Program Offices Practitioners and demonstrates how their organizations grow their open source knowledge and benefit from building a strategic vision and commitment around open source through an OSPO. This OSPO is based within the Porsche Automotive Company. The OSPO is structured with a Head of / lead and various streams, including the contribution and InnerSource team, in-house development team, supplier software development team, vulnerability lifecycle team, as well as the architecture and development team that builds tooling and services for the Porsche ecosystem, complemented by FOSS coordinators/ambassadors that are part of different business units
> [OSPO Book] add new use case: OSPO at Porsche

- ospo-book/content/en/02-chapter.md
- ospo-book/content/en/03-chapter.md
Performed a first, shallow check on chapter 2 and 3.
You can use this pull request to update the chapters further.
Fixes: #482
> [OSPO Book] Chapter 2 and 3 final review

- ospo-book/content/en/01-chapter.md
Reading through the text (which is FANTASTIC, btw!!) I stumbled across a duplicated passage. Maybe a merge conflict at some point?
> Remove duplicated passage

- whitepapers/business-value/README.md
related proposal: https://github.com/todogroup/ospology/discussions/481
approval by SC: https://github.com/todogroup/governance/blob/main/resolutions/approved/2024-08-05.md
> Create new oss in business WG formation

- newsletter/2024-11-07.md
Add new job post from the DPGA
> New job post (Update 2024-11-07.md)

- whitepapers/business-value/Roadmap.md
This file will serve as a guidance to our objectives, targets and priorities well documented. It is also going to be linked to the read.md file while having detailed timelines and milestones grouped together with the right outline or section.
> [OSS in Business] Created a Roadmap.md

- ospo-book/author-guide.md
The PR elaborates on the need to use markdown while writing guides and fixes some minor typos
> chore(author-guide.md): elaborate on using MD and fix typos

- newsletter/2023-10-02.md
- newsletter/2023-10-31.md
- newsletter/2023-12-20.md
- newsletter/2024-01-30.md
- newsletter/2024-02-29.md
- newsletter/2024-03-31.md
- newsletter/2024-06-07.md
- newsletter/2024-06-27.md
- newsletter/2024-09-03.md
- newsletter/2024-11-07.md
- newsletter/2024-12-20.md
- newsletter/2025-01-28.md
- newsletter/2025-02-27.md
Fixes the reference numbers of each newsletter file for records above 26.
We identified this issue in the analysis of PR #559
> [newsletter] fix: newsletters numbers from 26 onwards

- ospology-live/2025-march-amsterdam/README.md
Daniel Appelquist's and Sean Goggins' Slide deck links.
> Adding Slide links from OpenSSF and CHAOSS

- ospo-book/config.toml
- ospo-book/content/pt-br/00-chapter.md
- ospo-book/content/pt-br/01-chapter.md
- ospo-book/content/pt-br/02-chapter.md
- ospo-book/content/pt-br/03-chapter.md
- ospo-book/content/pt-br/04-chapter.md
- ospo-book/content/pt-br/05-chapter.md
- ospo-book/content/pt-br/06-chapter.md
- ospo-book/content/pt-br/07-chapter.md
- ospo-book/content/pt-br/_index.md
- ospo-book/content/pt-br/references.md
- ospo-book/content/pt-br/search.md
- ospo-book/content/pt-br/taxonomy.md
- ospo-book/content/pt-br/toc.md
- ospo-book/content/pt-br/use-cases.md
- ospo-book/i18n/pt-br.toml
add initial files to translation to Brazilian Portuguese
- Adding configs to support Brazilian Portuguese (pt-br) translated content
- Create a copy of all current English content so it can be translated
Related to #558
> docs(i18n/pt-BR): add initial files to translation to Brazilian Portuguese

- ospo-book/content/en/security-chapter.md
This markdown file was generated from the draft at: https://docs.google.com/document/d/1QiVIsy4RDV9RcSpnFzUfREtY0HPH_CrM3Zef6jWQn54/edit
The file needs to be renamed to be active.
> [OSPO Book] Create markdown file for security chapter

- ospo-book/translator-guide.md
Creating documentation in support of #556
> docs: Create translator-guide.md

- ospo-book/content/en/01-chapter.md
- ospo-book/content/en/02-chapter.md
- ospo-book/content/en/03-chapter.md
- ospo-book/content/en/04-chapter.md
- ospo-book/content/en/05-chapter.md
- ospo-book/content/en/06-chapter.md
- ospo-book/content/en/_index.md
This PR adds Markdown-powered footnotes to the OSPO Book chapter.
> chore(ospobook): add proper footnotes

- ospo-book/content/en/03-chapter.md
This PR fixes a few typos and lint the MD file so that it gives fewer warnings.
> chore(ospobook): fix grammar and lint MD file

- ospo-book/config.toml
- ospo-book/content/es/00-chapter.md
- ospo-book/content/es/01-chapter.md
- ospo-book/content/es/02-chapter.md
- ospo-book/content/es/03-chapter.md
- ospo-book/content/es/04-chapter.md
- ospo-book/content/es/05-chapter.md
- ospo-book/content/es/06-chapter.md
- ospo-book/content/es/07-chapter.md
- ospo-book/content/es/_index.md
- ospo-book/content/es/references.md
- ospo-book/content/es/search.md
- ospo-book/content/es/taxonomy.md
- ospo-book/content/es/toc.md
- ospo-book/content/es/use-cases.md
- ospo-book/i18n/es.toml
- Sync from the latest EN version
> docs(i18n/es): add initial files to translation to Spanish

- ospo-book/content/pt-br/00-chapter.md
Translation to Brazilian Portuguese - 00-chapter : Ref #558
> feat(i18n): translate 00-chapter to Brazilian Portuguese

- ospo-book/content/pt-br/taxonomy.md
Ref Issue #558 
@gioalmeida-ml
Could you review, please?
> feat(i18n): translate taxonomy.md to Brazilian Portuguese

- ospo-book/content/es/toc.md
> feat(i18n): translate TOC to Spanish

- ospo-book/content/es/taxonomy.md
Ref #579 
@fer-correa 
@bringani
> feat(i18n): translate taxonomy to Spanish

- ospo-book/content/es/01-chapter.md
Translation to Spanish - 01-chapter : Ref https://github.com/todogroup/ospology/issues/579
> feat(i18n): translate 01-chapter to Spanish

- ospo-book/content/es/02-chapter.md
Translation to Spanish - 02-chapter : Ref https://github.com/todogroup/ospology/issues/579
> feat(i18n): translate 02-chapter to Spanish

- ospo-book/content/es/03-chapter.md
Translation to Spanish - 03-chapter : Ref https://github.com/todogroup/ospology/issues/579
> feat(i18n): translate 03-chapter to Spanish

- whitepapers/business-value/README.md
- whitepapers/business-value/case_studies_and_stories.md
- whitepapers/business-value/communication_of_benefits_to_business_value.md
- whitepapers/business-value/glossary.md
- whitepapers/business-value/living_guide_for_business.md
- whitepapers/business-value/misconceptions_challenges.md
This is the first collection of base-files to start the collaboration.
The glossary.md was adapted and the case_studies_and_stories.md was created based on the discussion from friday august 1st.
For the other "chapters" in the "Initial outline" missing initial files were created and linked in the readme-"Initial outline"-section for convenient browsing.
> Opensource business guide

- meetings/Agenda_2025/Mar-24.md
- meetings/Agenda_2025/README.md
- ospo-book/author-guide.md
Please see these guides for authors and translators. 
Signed-off-by: Alice Sowerby <acsowerby@hotmail.com>
> Contributor role guides (Author guide and Translator guide)
