meetings/README.md
This commit clarifies the expected topics to be discussed during an OSPOlogy session and improves overall documentation on how to submit a proposal
=> Improve ospology meetings documentation

ospo-mindmap/GOVERNANCE.md
This new file sets the governance process, including:
- How contributors can become maintainers
- Feature request voting process
- Maintainer expectations
=> create governance.md for ospo mind map project

meetings/GOVERNANCE.md
OSPOlogy meeting topic proposals are now done via a CFP issue form. This info should be updated in the governance.md. This PR updates governance.md for ospology meetings
=> update governance.md for ospology meetings

ospo-mindmap/Content/ospomindmap.md
LFC193 is the first OpenChain Project's OSS training module that is under Linux Foundation courses.
=> Adding LFC193 under OS Legal Education

newsletter/2022-05-31.md
I was scrolling through the newsletter and noticed a typo on the GitHub role so I removed the "=".
=> Remove "=" typo

ospo-mindmap/Content/ospomindmap.md
I believe OSPO behavior should include collaboration with standards organizations and communities as well as with industry and cross industry. This PR adds "Standards Collaborative" as a "Behavior" in the OSPO Mind Map.
=> Add standards collaboration

ospo-mindmap/Content/ospomindmap.md
This PR surfaces "Sponsoring open source" higher up in the tree. It does this w/ 2 changes:
1. Separate "📝 Establish and Improve Open Source Policies and Processes" into:
* 📝 Establish and Improve Open Source Policies
* 💪 Establish and Improve Open Source Processes
2. Moving "Sponsoring open source" adjacent to "Creating Open Source" (instead of as a child)
=> surface 'Sponsors open source' higher up

ospology-live/2023-january-netherlands/presentations/chaoss-tooling-for-ospos-with-grimoirelab.md
Add link to slides of the presentation for OSPOlogy.live in Amsterdam with the title: "CHAOSS Tooling for OSPOs: how to build OSPO metrics in GrimoreLab"
Signed-off-by: Luis Cañas-Díaz <lcanas@bitergia.com>
=> Add link to presentation about CHAOSS tooling for OSPOs

ospo-book/chapters/01-chapter.md
During the OSPO Book #2 Contributor Call we decided to at a fifth role in Chapter 2: 
Act as a Gatekeeper: OSPOs can help to enforce OS policies and strengthen OS governance. This can help organizations to ensure compliance and mitigate OS security risks.
Since the role are also mentioned in chapter 1, I suggest to add this fith role in chapter one aswell.
=> [OSPO Book] Add Gatekeeper role to 01-chapter.md

ospo-book/content/en/toc.md
I found 2 typos in the table of content (toc) of the OSPO Book.  Here is a PR for fixing this.
=> Fix typos in ospo-book toc.

ospo-book/content/en/02-chapter.md, ospo-book/content/zh/02-chapter.md
To address issue https://github.com/todogroup/ospology/issues/393.
Some links were to a pdf on the Linux Foundation Website, others were to pdf externally to the lf website, and other to a page on the lf website.  Link to a page on the website, not directly to pdf.
=> Consistent linking to lf content.

ospo-book/content/en/02-chapter.md
This commit changes the antipatterns section for a recommendation section
=> [OSPO Book] Small update in Chapter 2

ospo-book/AUTHORS.md, ospo-book/content/en/07-chapter.md
Adding @UlisesGascon as a core contributor in the OSPO Book.
=> [OSPO Book] add new core contributor to the contributor list

ospo-book/content/en/04-chapter.md
This initial commit opens a PR so the community can make edits to content work on Chapter 4
- Who? [OSPO Book Working Group](https://ospobook.todogroup.org/07-chapter/)
- Where? [Feb 5th Contributors' Call](https://lists.todogroup.org/g/WG-ospo-book-project/message/47)
- How? [2024 Roadmap](https://lists.todogroup.org/g/WG-ospo-book-project/message/48)
> Newcomers are welcome to join our WG calls 🙋‍♀️
=> [OSPO Book] PR for Drafting Chapter 4 Content

ospo-book/content/en/03-chapter.md, ospo-book/content/en/04-chapter.md
Notes were recorded to [here](https://github.com/todogroup/ospology/discussions/448).
Contributors to the discussion were:
* Alessandro Lascu (iCubed srl)
* Anish Shanbhag (UC Berkeley)
* Matthias Meschede, @MMesch (Modus Create)
* Yann Hamdaoui, @yannham (Modus Create)
* Gergely Csatari (Nokia)
=> [OSPO Book]: Adding notes from KubeCon EU 2024 OSPO BoF

ospo-book/content/en/00-chapter.md
This pull request suggests to change the "what is this book about" section to stress what the purpose of an OSPO is. This is meant to make it clearer that the OSPO is a way to address the need of an organization to manage open source, not an end in itself.
There might be some more places in the book, where this could be made clearer with similar changes, but this section seems to be a good place to start with. If we agree on doing it this way, we can review and adapt other parts of the book as well, if needed.
=> Stress the purpose of the OSPO

newsletter/2025-02-27.md
Adds the following CFP dates and conferences to the newsletter which will be published on Thursday, February 27 2025
- June 23-24, 2025 [Open Source Summit North America](https://events.linuxfoundation.org/open-source-summit-north-america/) - CFP closed
- Aug 5, 2025 [Open Source Summit India](https://events.linuxfoundation.org/open-source-summit-india/) - CFP due 6 April, 2025
- Aug 25-27, 2025 [Open Source Summit Europe](https://events.linuxfoundation.org/open-source-summit-europe/) - CFP due 14 April, 2025
- August 26-28, 2025 [GopherCon](https://www.gophercon.com/) - CFP due 3 March, 2025
=> chore(2025-02-27.md): add CFP dates

.github/CODEOWNERS
The change reassigns ownership of the `.github/CODEOWNERS` and `.github/settings.yml` files to the `@todogroup/steering-committee` team.
=> fix(CODEOWNERS): secure repository with the right groups

ospo-book/content/en/toc.md
It resolves an issue where the table of contents incorrectly assigned chapter content. Specifically:
-   Chapter 5 now correctly reflects "Managing Open Source Security"
-   Chapter 6 now correctly reflects "Measuring the success and impact of your OSPO"
Related issue: #571
=> fix[ospo-book]: correct chapter 5 and 6 content in TOC

.vale/TODO/GenderBias.yml
Steward is also used for example as data steward. This is not a flight attendant.
=> fix(style): relax gender bias

ospo-book/content/en/05-chapter.md
Modify the security chapter ospo-book/content/en/05-chapter.md to meet the OSPO book's new style guide as described in https://github.com/todogroup/ospology/blob/main/.vale/TODO/README.md
=> Modify security chapter for style guide

README.md
This PR lint the `README` file and adds a link to the OSPO Book in the README.
=> chore(README): add OSPOBook link and lint MD

.vale/TODO/EmDashes.yml, .vale/TODO/Slash.yml, .vale/TODO/SpatialReferences.yml
**EmDashes**: The opposite of the Google and Microsoft style, but it works as described in the OSPO style guide.
**Slash**: Suggests to use 'and' instead of a slash.
**SpatialReference**: Works as intended, an author can always choose not to replace it.
Fixes: #622
=> feat(vale): checks for EmDashes, Slash, and SpatialReferences

ospo-book/content/en/references.md, ospo-book/content/es/references.md, ospo-book/content/pt-br/references.md, ospo-book/content/zh/references.md
The PR correctly links to the right endpoint and removes the duplicate `Porsche`.
=> chore(ospobook): fix case study links in references

whitepapers/business-value/.gitignore, whitepapers/business-value/README.md, whitepapers/business-value/content/en/_index.md, whitepapers/business-value/content/en/case_studies_and_stories.md, whitepapers/business-value/content/en/communication_of_benefits_to_business_value.md, whitepapers/business-value/content/en/engineering-vs-business-driven.md, whitepapers/business-value/content/en/glossary.md, whitepapers/business-value/content/en/living_guide_for_business.md, whitepapers/business-value/content/en/misconceptions_challenges.md, whitepapers/business-value/go.mod, whitepapers/business-value/go.sum, whitepapers/business-value/hugo.toml
This puts the actual content of the guide into the `content/en` directory and separates it from the other metadata like contribution guidelines and project setup. The minimal Hugo setup allows to show the content as Hugo-generated static website. Run `hugo server` to start it.
=> Add minimal Hugo setup using the hugo-book theme
